[2024-10-11 12:12:41: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 13, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:12:41: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85027 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49294)>
[2024-10-11 12:17:01: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:17:01: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85345 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49323)>
[2024-10-11 12:18:42: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:18:42: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85345 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49331)>
[2024-10-11 12:18:49: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:18:49: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85345 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49331)>
[2024-10-11 12:19:07: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:19:07: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85498 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49342)>
[2024-10-11 12:20:05: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:20:05: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85497 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49351)>
[2024-10-11 12:20:07: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:20:07: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85497 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49351)>
[2024-10-11 12:20:31: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:20:31: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85497 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49361)>
[2024-10-11 12:20:48: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:20:48: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85497 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49367)>
[2024-10-11 12:21:20: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:21:20: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85497 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49375)>
[2024-10-11 12:21:37: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:21:37: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85497 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49381)>
[2024-10-11 12:21:54: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:21:54: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85497 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49387)>
[2024-10-11 12:22:20: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:22:20: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85497 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49395)>
[2024-10-11 12:25:49: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:25:49: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85497 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49395)>
[2024-10-11 12:26:24: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:26:24: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85497 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49413)>
[2024-10-11 12:29:25: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:29:25: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85497 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49429)>
[2024-10-11 12:29:49: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:29:49: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85497 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49437)>
[2024-10-11 12:34:10: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:34:10: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 145 500 <socket.socket fd=5, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49459)>
[2024-10-11 12:36:30: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:36:33: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 145 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49468)>
[2024-10-11 12:37:32: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:37:35: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 145 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49468)>
[2024-10-11 12:38:39: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:38:45: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85511 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49490)>
[2024-10-11 12:38:48: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:38:55: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:39:00: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85512 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49499)>
[2024-10-11 12:39:05: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:39:07: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85512 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49499)>
[2024-10-11 12:39:14: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:39:18: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:39:22: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 145 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49507)>
[2024-10-11 12:39:46: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:39:52: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 145 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49507)>
[2024-10-11 12:40:06: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:40:11: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 145 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49507)>
[2024-10-11 12:40:35: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-11 12:40:38: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85508 500 <socket.socket fd=12, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49518)>
[2024-10-12 09:17:41: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-12 09:17:44: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85027 500 <socket.socket fd=5, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49257)>
[2024-10-12 09:18:29: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    print(asd)
          ^^^
NameError: name 'asd' is not defined
[2024-10-12 09:18:32: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 85165 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49283)>
[2024-10-12 10:01:29: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    return HttpResponse(render(request, "profiles/index.html"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 523, in parse
    self.unclosed_block_tag(parse_until)
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 586, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 2: 'block'. Looking for one of: endblock.
[2024-10-12 10:01:33: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 174705 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 50089)>
[2024-10-12 10:01:51: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    return HttpResponse(render(request, "profiles/index.html"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 523, in parse
    self.unclosed_block_tag(parse_until)
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 586, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 2: 'block'. Looking for one of: endblock.
[2024-10-12 10:01:56: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 174705 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 50097)>
[2024-10-12 10:02:08: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    return HttpResponse(render(request, "profiles/index.html"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 523, in parse
    self.unclosed_block_tag(parse_until)
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 586, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 2: 'block'. Looking for one of: endblock.
[2024-10-12 10:02:14: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 174705 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 50108)>
[2024-10-12 10:02:27: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    return HttpResponse(render(request, "profiles/index.html"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 523, in parse
    self.unclosed_block_tag(parse_until)
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 586, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 2: 'block'. Looking for one of: endblock.
[2024-10-12 10:02:32: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 174705 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 50116)>
[2024-10-12 10:02:39: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    return HttpResponse(render(request, "profiles/index.html"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 523, in parse
    self.unclosed_block_tag(parse_until)
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 586, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 2: 'block'. Looking for one of: endblock.
[2024-10-12 10:02:45: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 174715 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 50122)>
[2024-10-12 10:02:54: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    return HttpResponse(render(request, "profiles/index.html"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 573, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 6: 'static'. Did you forget to register or load this tag?
[2024-10-12 10:02:59: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 173291 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 50128)>
[2024-10-12 10:03:14: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    return HttpResponse(render(request, "profiles/index.html"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 573, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 6: 'static'. Did you forget to register or load this tag?
[2024-10-12 10:03:17: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 173291 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 50135)>
[2024-10-12 10:03:34: ERROR/django.request] Internal Server Error: /profiles/me/ 500 <WSGIRequest: GET '/profiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/django_examples/profiles/views/me.py", line 12, in show_template
    return HttpResponse(render(request, "profiles/index.html"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/base.py", line 573, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 6: 'static'. Did you forget to register or load this tag?
[2024-10-12 10:03:37: ERROR/django.server] "GET /profiles/me/ HTTP/1.1" 500 173291 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 50142)>
[2024-10-12 11:31:26: ERROR/django.request] Internal Server Error: /userprofiles/me/ 500 <WSGIRequest: GET '/userprofiles/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/blumenhorizon/userprofiles/views/me.py", line 12, in show_template
    return HttpResponse(render(request, "userprofiles/index.html"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: userprofiles/index.html
[2024-10-12 11:31:29: ERROR/django.server] "GET /userprofiles/me/ HTTP/1.1" 500 102373 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 50093)>
[2024-10-12 11:31:56: ERROR/django.request] Internal Server Error: /profile/me/ 500 <WSGIRequest: GET '/profile/me/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/blumenhorizon/userprofiles/views/me.py", line 12, in show_template
    return HttpResponse(render(request, "userprofiles/index.html"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: userprofiles/index.html
[2024-10-12 11:31:58: ERROR/django.server] "GET /profile/me/ HTTP/1.1" 500 102308 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 50101)>
[2024-10-12 12:09:25: ERROR/django.request] Internal Server Error: /profile/ 500 <WSGIRequest: GET '/profile/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/views/generic/detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/example/.venv/lib/python3.12/site-packages/django/views/generic/detail.py", line 46, in get_object
    raise AttributeError(
AttributeError: Generic detail view UserDetailView must be called with either an object pk or a slug in the URLconf.
[2024-10-12 12:09:28: ERROR/django.server] "GET /profile/ HTTP/1.1" 500 100580 500 <socket.socket fd=4, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 50563)>
[2024-10-13 06:45:25: ERROR/django.request] Internal Server Error: /accounts/signup/ 500 <WSGIRequest: GET '/accounts/signup/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/blumenhorizon/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/blumenhorizon/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/blumenhorizon/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/blumenhorizon/.venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/blumenhorizon/.venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/blumenhorizon/.venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: accounts/authorization/sign_up.html
[2024-10-13 06:45:27: ERROR/django.server] "GET /accounts/signup/ HTTP/1.1" 500 103594 500 <socket.socket fd=5, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 55320)>
[2024-10-13 06:45:48: ERROR/django.request] Internal Server Error: /accounts/signup/ 500 <WSGIRequest: GET '/accounts/signup/'>
Traceback (most recent call last):
  File "/Users/levinsxn/Documents/blumenhorizon/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/blumenhorizon/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/blumenhorizon/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/blumenhorizon/.venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/blumenhorizon/.venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levinsxn/Documents/blumenhorizon/.venv/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: accounts/authorization/sign_up.html
[2024-10-13 06:45:50: ERROR/django.server] "GET /accounts/signup/ HTTP/1.1" 500 103731 500 <socket.socket fd=5, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 55320)>
